# Generated by Django 2.1 on 2018-08-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
