# Generated by Django 2.1 on 2018-08-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20180810_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
