# Generated by Django 2.1 on 2018-08-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20180810_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.FileField(upload_to='C:/serverstuff'),
        ),
    ]
