# Generated by Django 2.1 on 2018-08-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
