# Generated by Django 2.1 on 2018-08-28 11:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0019_costumer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Profile',
        ),
    ]
