# Generated by Django 2.1 on 2018-08-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20180828_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
