# Generated by Django 2.1 on 2018-08-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
