# Generated by Django 2.1 on 2018-08-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_profile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
    ]
