# Generated by Django 2.1 on 2018-08-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_profile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
    ]
