# Generated by Django 2.1.1 on 2018-09-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0030_remove_profile_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(upload_to='media/products/images/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='media/products/images/')),
                ('image3', models.FileField(blank=True, null=True, upload_to='media/products/images/')),
                ('image4', models.FileField(blank=True, null=True, upload_to='media/products/images//')),
                ('image5', models.FileField(blank=True, null=True, upload_to='media/products/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
        migrations.AddField(
            model_name='product_images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Product'),
        ),
    ]
