# Generated by Django 2.1.1 on 2018-09-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0032_auto_20180908_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
    ]
