# Generated by Django 2.1.1 on 2018-09-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0033_auto_20180908_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.FileField(default=None, upload_to='media/products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/products/images//'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/products/images/'),
        ),
    ]
