# Generated by Django 2.1.1 on 2018-09-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0034_auto_20180908_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='product_price_value',
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
