# Generated by Django 2.1.1 on 2018-09-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0035_auto_20180909_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
