# Generated by Django 2.1.1 on 2018-09-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0039_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
    ]
