# Generated by Django 2.1.1 on 2018-09-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0040_auto_20180921_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
